#!/bin/bash

threads=40
reads=canu_corr150x.min1kb.renamed.correctedReads.fasta.gz
out_dir=/data/flye_assembly/flye_assembly_1kb_reads

flye \
  --nano-corr $reads \
  --genome-size 500m \
  --out-dir $out_dir \
  -t $threads \
